### Agregar un nuevo proyecto - Falla
POST http://localhost:8080/proyecto
Content-Type: application/json
Accept: application/json

{
  "nombreProyecto": "Proyecto de prueba",
  "montoRecaudar": 100,
  "descripcion": "El siguiente proyecto es un dato de prueba"
}
### Muestra los proyectos Vigentes - Funcioma
GET http://localhost:8080/estado/1
accept: application/json
### Muestra los proyectos en proceso - Funcioma
GET http://localhost:8080/estado/2
accept: application/json
### Muestra los proyectos Finalizados - Funcioma
GET http://localhost:8080/estado/3
accept: application/json
### Muestra todos los proyectos - Funcioma
GET http://localhost:8080/estado/4
accept: application/json
### Busqueda de proyecto
POST http://localhost:8080/nombreProyecto/proyecto
accept: application/json
### Busqueda de proyecto por id - Funciona
GET http://localhost:8080/nombreProyecto/1