### Agregar un nuevo proyecto - Falla
POST http://localhost:8081/proyecto
Content-Type: application/json
Accept: application/json

{
  "nombreProyecto": "Proyecto de prueba x",
  "montoRecaudar": -1,
  "descripcion": "El siguiente proyecto es un dato de prueba"
}
### Muestra los proyectos Vigentes - Funcioma
GET http://localhost:8081/foo/estado/1
accept: application/json
### Muestra los proyectos en proceso - Funcioma
GET http://localhost:8081/foo/estado/2
accept: application/json
### Muestra los proyectos Finalizados - Funcioma
GET http://localhost:8081/foo/estado/3
accept: application/json
### Muestra todos los proyectos - Funcioma
GET http://localhost:8081/foo/estado/4
accept: application/json
### Busqueda de proyecto por id - Funciona
GET http://localhost:8081/foo/proyecto/1
### Pagina PRicipal
GET http://localhost:8081/foo/paginaprincipal
