### Tomar un contrato
GET http://localhost:8080/contrato/1
accept: application/json

### Agrega un nuevo donador
POST http://localhost:8080/donador
Content-Type: application/json
Accept: application/json

{
  "id_usuario": 1,
  "id_contrato": 2
}

### Muestra los proyectos Vigentes
GET http://localhost:8080/donador/1
accept: application/json

### Buscar un proyecto por su nombre
GET http://localhost:8080/persona
accept: application/json

### Muestra los proyectos en proceso
POST http://localhost:8080/donador
accept: application/json

### Busqueda de donador por nombre
GET http://localhost:8080/donador/{{nombre_persona}}}
accept: application/json

###
GET http://localhost:8080/donador
accept: application/json

### Agrega una nueva donacion
POST http://localhost:8080/donacion
Content-Type: application/json
accept: application/json

{
  "id_proyecto": 1,
  "id_donador": 1,
  "monto": 1000,
  "hora": "14:00",
  "fecha_donacion": "5/13/2021"
}

### Mostrar todas las personas
GET http://localhost:8080/persona

###
GET http://localhost:8080/persona/2